# These are supported funding model platforms

github: # wolffcatskyy  # Uncomment if you enable GitHub Sponsors
# patreon: username
ko_fi: # your_kofi_username
buy_me_a_coffee: # your_bmac_username
# custom: ["https://example.com/donate"]
